# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20151224_2148'),
        ('restaurants', '0002_auto_20151224_2201'),
    ]

    operations = [
    ]
