# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='type',
            new_name='style',
        ),
    ]
