# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20151230_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='style',
        ),
    ]
