# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('restaurants', '0007_remove_restaurant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='is_category_of', to='categories.Category'),
        ),
    ]
