# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_catalogue',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
            preserve_default=False,
        ),
    ]
