# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0004_auto_20160101_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_catalogue',
            old_name='category',
            new_name='categories',
        ),
    ]
