# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel_products_branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rel_product_branch',
            old_name='id_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='rel_product_branch',
            old_name='id_product',
            new_name='product',
        ),
    ]
