# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofiles',
            name='admin',
            field=models.NullBooleanField(),
        ),
    ]
