# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20160103_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='direccion',
            field=models.TextField(blank=True),
        ),
    ]
