# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20160108_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
