# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_remove_customerprofile_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Customers'),
        ),
    ]
