# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_customerprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_picture',
        ),
    ]
