# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.CustomerProfiles'),
            preserve_default=False,
        ),
    ]
