# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0004_shopping_cart_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
