# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_carts', '0005_auto_20160109_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='customer',
            new_name='user',
        ),
    ]
