# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rel_products_shopping_carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rel_product_shopping_cart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
