# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20151224_2201'),
        ('products', '0002_auto_20151224_2148'),
    ]

    operations = [
    ]
