# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20151229_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='public_name',
            new_name='name',
        ),
    ]
