# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0004_auto_20160101_0212'),
        ('products', '0005_auto_20160101_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='private_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_super',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_catalogue.Product_catalogue'),
            preserve_default=False,
        ),
    ]
