# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
