# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel_users_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rel_user_product',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rel_user_product',
            old_name='id_user',
            new_name='user',
        ),
    ]
