# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel_users_products', '0002_auto_20151229_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rel_user_product',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
