# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fistr_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
