# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_payment', models.CharField(max_length=255)),
            ],
        ),
    ]
