# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
