# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20151230_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='payment_date_time',
        ),
    ]
