# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('types_of_payment', '0001_initial'),
        ('orders', '0006_auto_20160101_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_of_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='types_of_payment.TypeOfPayment'),
            preserve_default=False,
        ),
    ]
